
logging:
  level:
    root: INFO
    com.kbe5.api: INFO

spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            time_zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER_NAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    ssl:
      enabled: true
    listener:
      simple:
        concurrency: 6

fcm:
  firebase_config_path: ${FIREBASE_PATH}

server:
  port: 8080
  tomcat:
    threads:
      max: 1000
      min-spare: 200
    accept-count: 5000 # 대기 큐
    connection-timeout: 20000 # 타임아웃x
    max-connections: 15001 #서버가 수락하고 처리할 수 있는 최대 연결수
