spring:
  config:
    import:
      - optional:file:.env

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  messages:
    basename: messages
    encoding: UTF-8

  profiles:
    active: local
