spring:
  config:
    import:
      - optional:file:.env
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul

  messages:
    basename: messages
    encoding: UTF-8

fcm:
  firebase_config_path: ${FIREBASE_CONFIG}
