spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          jdbc:
            time_zone: Asia/Seoul
