spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
